language: python
python:
  - "3.12"

os: linux
dist: focal

cache: pip

install:
  - python -m pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt

before_script:
  - export DJANGO_SETTINGS_MODULE=boutique_house.settings
  - export SECRET_KEY="travis-ci-secret-key"
  - export DEVELOPMENT=1
  - export DJANGO_TEST=1

script:
  - coverage run manage.py test

after_success:
  - codecov
