# Generated by Django 6.0.6 on 2026-06-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_label', models.CharField(default='Summer Edit', max_length=80)),
                ('heading', models.CharField(default='The new collections are here', max_length=140)),
                ('subheading', models.TextField(default='Soft, sculptural, editorial. A quiet, modern counterpoint that keeps the UI clean.')),
                ('cta_label', models.CharField(default='Shop Now', max_length=40)),
                ('portrait_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Hero',
                'verbose_name_plural': 'Home Hero Entries',
                'ordering': ['-updated_at'],
            },
        ),
    ]
